export const items =  [
    {
      id: 1,
      category: 'comedy',
      title: "chennai express",
      imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.TLpyB4JbaUlJ3O58YlmhowHaFj&pid=Api&P=0&h=180',
      Actor: 'SRK',
      releasedata: '8/8/2013',
    },
    {
        id: 2,
        category: 'Action',
        title: "KGF",
        imgSrc: 'https://tse3.mm.bing.net/th?id=OIF.7xZKdu59nSkjbrCctYAgog&pid=Api&P=0&h=180',
        Actor: 'yash',
        releasedata: '21/12/2018',
      },
      {
        id: 3,
        category: 'Action',
        title: "Pushpa",
        imgSrc: 'https://tse1.mm.bing.net/th?id=OIP.rMsMGNc9IEK7U5xP1MyGgwHaLG&pid=Api&P=0&h=180',
        Actor: 'Allu arjun',
        releasedata: '17/12/2021',
      },
      {
        id: 4,
        category: 'comedy',
        title: "Hera Pheri",
        imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.jHRRfbyGWR7uyLTq3Bn52AHaJ4&pid=Api&P=0&h=180',
        Actor: 'Akshay kumar',
        releasedata: '12/8/2000',
      },
      {
        id: 5,
        category: 'Action',
        title: "Road House",
        imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.wNfEQnctWTG3eW5F-nqLJgAAAA&pid=Api&P=0&h=180',
        Actor: 'Jake Gyllenhaal',
        releasedata: '2024',
      },
      {
        id: 6,
        category: 'comedy',
        title: "chennai express",
        imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.TLpyB4JbaUlJ3O58YlmhowHaFj&pid=Api&P=0&h=180',
        Actor: 'SRK',
        releasedata: '8/8/2013',
      },
      {
        id: 7,
        category: 'comedy',
        title: "Golmaal",
        imgSrc: 'https://tse3.mm.bing.net/th?id=OIP.XzZHuMtjYL5qbDvREHUuNAHaKK&pid=Api&P=0&h=180',
        Actor: 'Ajay devgan',
        releasedata: '2006',
      },
      {
        id: 8,
        category: 'Action',
        title: "kantara",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.Am4rOC33neyGVUTXq5134AHaKb&pid=Api&P=0&h=180',
        Actor: 'Rishabh Shetty',
        releasedata: '30/9/2022',
      },
    
  ]